apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-example-backend-deployment
  namespace: poc-dapr
  labels:
    app: dapr-example-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-example-backend
  template:
    metadata:
      labels:
        app: dapr-example-backend
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr-example-backend"
        dapr.io/app-port: "80"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
      - name: dapr-example-backend
        image: saeedmaghdam/poc-dapr-example-backend:1.1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Deployment"
        imagePullPolicy: Always