apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: poc-dapr
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-master.infra.svc.cluster.local:6379
  - name: redisPassword
    secretKeyRef:
      name: redis
      key: redis-password