apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-example-deployment
  namespace: poc-dapr
  labels:
    app: dapr-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-example
  template:
    metadata:
      labels:
        app: dapr-example
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr-example"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
      - name: dapr-example
        image: saeedmaghdam/poc-dapr-example:1.5
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: Always